  version: '3'
  services:
    db:
      image: 'postgres:latest'
      environment:
        POSTGRES_USER: postgres 
        POSTGRES_PASSWORD: 123nitheshANAND 
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
      networks:
        - app_network
      restart: unless-stopped
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: anand@infraweigh.co
        PGADMIN_DEFAULT_PASSWORD: 123nitheshANAND
      ports:
        - "5050:80"

    redis:
      image: 'redis:latest'
      command: >
          --requirepass 123nitheshANAND
      ports:
        - 6379:6379
      networks:
        - app_network
      restart: unless-stopped
  networks:
    app_network:
      driver: bridge