export enum SETTING_KEYS {
  PRODUCTION_UNIT = 'PRODUCTION_UNIT',
  PRODUCTION_UNIT_PRODUCTION_METRICS = 'PRODUCTION_UNIT_PRODUCTION_METRICS',
  PRODUCTION_UNIT_MAINTENANCE_METRICS = 'PRODUCTION_UNIT_MAINTENANCE_METRICS',
}
