# This workflow will build and push a Docker image to Amazon ECR

name: Build and Push Docker Image to AWS ECR

on:
  # Trigger the workflow on push to main branch
  push:
    branches: [master]

  # Or trigger the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - run: docker build --tag easy-cmms-prod-server:production .
      
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1
          image: easy-cmms-prod-server:production
